SetColumns(0); R<x>:=PolynomialRing(Rationals()); checked:=0;
id:="5.b"; C:=SimplifiedModel(HyperellipticCurve(R![-344,348,-334,17,14,-36,-8],R![0]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 121;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="2.4.b"; C:=SimplifiedModel(HyperellipticCurve(R![-16,6,-6,11,1,3],R![1,0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 225;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="2.8.b"; C:=SimplifiedModel(HyperellipticCurve(R![-214,465,-279,447,-305,60,-175],R![1,0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 225;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="4.4.b"; C:=SimplifiedModel(HyperellipticCurve(R![448,0,-7,0,-2,0,7],R![0,0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 225;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="4.8.b"; C:=SimplifiedModel(HyperellipticCurve(R![0,-15,-5,-5],R![0,1,0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 225;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="5.5.a"; C:=SimplifiedModel(HyperellipticCurve(R![-2,4,2,5,2,1],R![1,1,1,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 121;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="7.7.a"; C:=SimplifiedModel(HyperellipticCurve(R![869675859,0,3232987,0,3025,0,1],R![0]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 53958996;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="2.2.2.b"; C:=SimplifiedModel(HyperellipticCurve(R![0,1,32,268,129,16],R![0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 315;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
id:="2.4.4.b"; C:=SimplifiedModel(HyperellipticCurve(R![0,15,40,0,161,-240],R![0,1]));
products:=[* s : s in RichelotIsogenousSurfaces(Jacobian(C)) | Type(s) eq SetCart *];
assert #products gt 0; P:=products[1]; assert BaseRing(P[1]) cmpeq Rationals() and BaseRing(P[2]) cmpeq Rationals();
assert Conductor(P[1])*Conductor(P[2]) eq 225;
printf "%o elliptic conductors=%o,%o genus2 conductor=%o\n",id,Conductor(P[1]),Conductor(P[2]),Conductor(P[1])*Conductor(P[2]);checked+:=1;
assert checked eq 9; print "NINE_CONDUCTOR_CORRECTIONS_VERIFIED"; quit;
